<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Appointments Report - HealthCare</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 11px;
            color: #333;
            line-height: 1.6;
            padding: 30px;
        }
        .header {
            border-bottom: 3px solid #3B82F6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #3B82F6;
            font-size: 28px;
            margin-bottom: 5px;
        }
        .header .subtitle {
            color: #666;
            font-size: 14px;
        }
        .report-meta {
            background: #F3F4F6;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .report-meta table {
            width: 100%;
        }
        .report-meta td {
            padding: 5px 0;
        }
        .report-meta strong {
            color: #1F2937;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 25px;
        }
        .stat-card {
            display: table-cell;
            width: 25%;
            padding: 15px;
            text-align: center;
            border-right: 1px solid #E5E7EB;
        }
        .stat-card:last-child {
            border-right: none;
        }
        .stat-card .number {
            font-size: 24px;
            font-weight: bold;
            color: #3B82F6;
        }
        .stat-card .label {
            color: #6B7280;
            font-size: 10px;
            text-transform: uppercase;
            margin-top: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table.data-table thead {
            background: #1F2937;
            color: white;
        }
        table.data-table th {
            padding: 12px 8px;
            text-align: left;
            font-weight: 600;
            font-size: 10px;
            text-transform: uppercase;
        }
        table.data-table tbody tr {
            border-bottom: 1px solid #E5E7EB;
        }
        table.data-table tbody tr:nth-child(even) {
            background: #F9FAFB;
        }
        table.data-table td {
            padding: 10px 8px;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 9px;
            font-weight: 600;
            text-transform: uppercase;
        }
        .status-completed { background: #D1FAE5; color: #065F46; }
        .status-pending { background: #FEF3C7; color: #92400E; }
        .status-confirmed { background: #DBEAFE; color: #1E40AF; }
        .status-cancelled { background: #FEE2E2; color: #991B1B; }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #E5E7EB;
            text-align: center;
            color: #6B7280;
            font-size: 9px;
        }
        .page-number::after {
            content: counter(page);
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>HealthCare</h1>
        <div class="subtitle">Appointments Report</div>
    </div>

    <!-- Report Meta Information -->
    <div class="report-meta">
        <table>
            <tr>
                <td width="50%"><strong>Report Period:</strong> {{ \Carbon\Carbon::parse($date_from)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($date_to)->format('M d, Y') }}</td>
                <td width="50%"><strong>Generated:</strong> {{ now()->format('M d, Y H:i') }}</td>
            </tr>
            <tr>
                <td><strong>Total Appointments:</strong> {{ $total }}</td>
                <td><strong>Generated By:</strong> Admin</td>
            </tr>
        </table>
    </div>

    <!-- Statistics Cards -->
    <div class="stats-grid">
        <div class="stat-card">
            <div class="number">{{ $total }}</div>
            <div class="label">Total</div>
        </div>
        <div class="stat-card">
            <div class="number">{{ $completed }}</div>
            <div class="label">Completed</div>
        </div>
        <div class="stat-card">
            <div class="number">{{ $pending }}</div>
            <div class="label">Pending</div>
        </div>
        <div class="stat-card">
            <div class="number">{{ $cancelled }}</div>
            <div class="label">Cancelled</div>
        </div>
    </div>

    <!-- Data Table -->
    <table class="data-table">
        <thead>
            <tr>
                <th width="5%">#</th>
                <th width="20%">Patient</th>
                <th width="20%">Doctor</th>
                <th width="15%">Date</th>
                <th width="10%">Time</th>
                <th width="20%">Type</th>
                <th width="10%">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($appointments as $i => $appointment)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $appointment->patient->first_name ?? 'N/A' }}</td>
                <td>Dr. {{ $appointment->doctor->first_name ?? 'N/A' }}</td>
                <td>{{ \Carbon\Carbon::parse($appointment->appointment_date)->format('M d, Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($appointment->appointment_time)->format('h:i A') }}</td>
                <td>{{ ucfirst(str_replace('-', ' ', $appointment->appointment_type ?? 'N/A')) }}</td>
                <td>
                    <span class="status-badge status-{{ $appointment->status }}">
                        {{ ucfirst($appointment->status) }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>HealthCare - Medical Management System | Confidential Report</p>
        <p>Page <span class="page-number"></span></p>
    </div>
</body>
</html>